# Minimal schema for the default 'movies' repository
version: 0.1
name: movies
allow_extensions:
  - .md
  - .css
  - .png
  - .jpg
  - .jpeg
  - .gif
  - .svg
  - .json
  - .wasm
  - .html
  - .txt
  - .xml
  - .pdf
content:
  collections:
    movies:
      path: "data/movies"
      file: "*.json"
      fields:
        - key: title
          type: string
          required: true
        - key: year
          type: number
          required: true
        - key: ipfs_hash
          type: string
          required: true
        - key: poster
          type: string
          required: false
      constraints:
        max_file_size_kb: 256
        allowed_mime:
          - application/json
